# Generated by Django 5.0.1 on 2024-05-05 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_postlike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
